name: basket_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  app_tracking_transparency: ^2.0.4
  shared_preferences: ^2.2.3
  flutter_inappwebview: ^5.7.2+3
  flutter_svg: ^2.0.10+1
  firebase_messaging: ^14.2.2
  firebase_analytics:
  firebase_core: 
  hive: ^2.2.3
  intl: ^0.19.0
  overlay_support: ^2.1.0
  firebase_remote_config:

  appsflyer_sdk: 
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.0
  mask_text_input_formatter: ^2.9.0
  dio: ^5.5.0+1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: P
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf